### ISSUE TITLE
Cron copy the theme directory to theme website

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-curated-themes-list#1]
Hi @petecooper, when you get a spare few moments could you possibly set this up like you did for the plugins curated list, whereby the directory `library-of-themes` is copied over to the root directory of the themes website on our server.

It'll function in a very similar manner to the current plugins site, when the themes site is more finished.

Cheers!

**Comment by petecooper** [comment]
Yep - should have time this evening if I'm done with stuff, otherwise this weekend.

**Comment by petecooper** [comment]
OK, should be done. Every quarter-past and quarter-to the hour, with a 15 second delay so the plugins run happens first. Will leave open until first run in 17 mins, then close if working.

**Comment by petecooper** [comment]
Can be closed (I can't).

**Comment by philwareham** [comment]
Thanks Pete! I'll pick this up again early next week.
